### ISSUE TITLE
Support globalThis

### ISSUE THREAD

**Issue by Standard8** [eslint/eslint#12670]
**The version of ESLint you are using.** 6.7.2

**The problem you want to solve.**

`globalThis` is now a [tc 39 stage 4 proposal](https://github.com/tc39/proposal-global). ESLint should now be updated to recognise this.

**Your take on the correct solution to problem.**

Update the environment list to add `globalThis`

**Are you willing to submit a pull request to implement this change?** Yes

**Comment by Standard8** [comment]
I've created #12671 for basic support of the global in the environment. Now I think about it a little more, I'm not sure if there's more follow-up work that ESLint will need to do to understand variables created via `globalThis`.

**Comment by kaicataldo** [comment]
Agreed that we should update this. We'll also have to check and see if we need to update any of our core rules to account for this.

**Comment by mysticatea** [comment]
I added this to `7.0.0` board because I think this is a breaking change (e.g., `no-redeclare` may raise new warnings).

There are several rules we need to update. For example, the rules that check `window.*` should check `globalThis.*` as well.

**Comment by yeonjuan** [comment]
Maybe,,, Is someone working on it? :)

**Comment by mdjermanovic** [comment]
@mysticatea some of the rules you listed in [this comment](https://github.com/eslint/eslint/pull/12671#issuecomment-567868899) are checking `window.*` via `ReferenceTracker`.

Should these rules now explicitly pass "globalThis" in `options.globalObjectNames`  (along with the current defaults "global", "self", and "window"), or should this be an update in `eslint-utils` to add `globalThis` to the default list for `options.globalObjectNames`?

**Comment by mysticatea** [comment]
@yeonjuan Probably not.

I published an `eslint-utils` update for `globalThis`.

**Comment by yeonjuan** [comment]
Ok, I'll try it. :)

**Comment by mdjermanovic** [comment]
PR #12774

**Comment by btmills** [comment]
@yeonjuan thank you for implementing most of this in #12774! I realize we merged it before #12775 so you didn't have a chance to [add `globalThis` support to `no-implied-eval`](https://github.com/eslint/eslint/pull/12757/files#r366681633) now that you've updated it. Would you like to update that last rule to fully close that issue? If you do, feel free to ping me in the PR so I'll get an email and can review it quickly.

**Comment by yeonjuan** [comment]
@btmills 
Sure : ). PR #13105  will support `globalThis` in no-implied-eval

**Comment by janosh** [comment]
I'm still seeing `'globalThis' is not defined. eslint(no-undef)` in v7.1.

From reading [the release notes](https://eslint.org/blog/2020/05/eslint-v7.0.0-released#enhancements), I thought support for `globalThis` landed in v7. Am I missing something?

**Comment by kaicataldo** [comment]
Do you have the [`es2020` environment](https://eslint.org/docs/user-guide/configuring#specifying-environments) enabled?

**Comment by janosh** [comment]
@kaicataldo Ah, that was the missing piece. Thanks a lot!
