### ISSUE TITLE
template-curly-spacing rule exception

### ISSUE THREAD

**Issue by kristianpd** [eslint/eslint#13839]
**Tell us about your environment**

Node version: v14.4.0
npm version: v6.14.4
Local ESLint version: v7.13.0 (Currently used)

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

@babel/eslint-parser

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Not exactly production ready code, but while testing something out I stumbled across a line of JS that breaks the `template-curly-spacing` rule:

```js
const nonParameterArgs = this.context.module.controllerConstructor.args.filter(a => !this[`${a}Target`]?.selectedOptions[0]?.hasAttribute('data-parameter-id')).map(a => this[`${a}Argument`]);
```

**What did you expect to happen?**
Not raise an exception

**What actually happened? Please include the actual, raw output from ESLint.**
The linter broke

Offending line: https://github.com/eslint/eslint/blob/master/lib/rules/template-curly-spacing.js#L52

```bash
TypeError: Cannot read property 'value' of null
Occurred while linting /myrepo/app/javascript/controllers/plots/plot_controller.js:51
    at checkSpacingBefore (/myrepo/node_modules/eslint/lib/rules/template-curly-spacing.js:52:24)
    at TemplateElement (/myrepo/node_modules/eslint/lib/rules/template-curly-spacing.js:136:17)
    at /myrepo/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/myrepo/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/myrepo/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/myrepo/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/myrepo/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/myrepo/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /myrepo/node_modules/eslint/lib/linter/linter.js:952:32
error Command failed with exit code 2.
```

**Are you willing to submit a pull request to fix this bug?**
Not right now, sorry

**Comment by mdjermanovic** [comment]
Hi @kristianpd, thanks for the issue!

Are you using `babel-eslint` or `@babel/eslint-parser`?

This was a known issue in `babel-eslint`, but should have been fixed in `@babel/eslint-parser`.

(`babel-eslint` is now `@babel/eslint-parser`)

**Comment by kristianpd** [comment]
I'm still using `babel-eslint`, will look at upgrading tomorrow and will report back

**Comment by susiwen8** [comment]
I have encountered same problem.

Using `@babel/eslint-parser` still have this issue.

**Comment by mdjermanovic** [comment]
> I have encountered same problem.
> 
> Using `@babel/eslint-parser` still have this issue.

Can you please share an example where this error occurs?

**Comment by susiwen8** [comment]
> > I have encountered same problem.
> > Using `@babel/eslint-parser` still have this issue.
> 
> Can you please share an example where this error occurs?

Sure

```js
const a = {
    b: `111${1}`
}
```

`@babel/eslint-parser` version is 7.12.1
`eslint` version 7.14

and strange thing is in one particulate repo has this issue, where ever I use string template in `Object`, this error will occur,  but in other repo, no error.

```shell
Oops! Something went wrong! :(

ESLint: 7.14.0

TypeError: Cannot read property 'value' of null
Occurred while linting /Users/susiwen/Documents/project/test.ts:3
    at checkSpacingBefore (/Users/susiwen/Documents/project/node_modules/eslint/lib/rules/template-curly-spacing.js:52:24)
    at TemplateElement (/Users/susiwen/Documents/project//node_modules/eslint/lib/rules/template-curly-spacing.js:136:17)
    at /Users/susiwen/Documents/project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/susiwen/Documents/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/susiwen/Documents/project/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/susiwen/Documents/project/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/susiwen/Documents/project/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/susiwen/Documents/project/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /Users/susiwen/Documents/project/node_modules/eslint/lib/linter/linter.js:952:32
```

**Comment by mdjermanovic** [comment]
> ```js
> const a = {
>     b: '111',
>     c: `111${1}`
> }
> ```
> 
> 
> @babel/eslint-parser version is 7.12.1
> eslint version 7.14

I couldn't reproduce this. Tried with the following config and source code:

```js
module.exports = {
  parser: "@babel/eslint-parser",
  rules: {
    "template-curly-spacing": "error"
  }
};
```

```js
const a = {
  b: '111',
  c: `111${1}`
}
```

Does your configuration use `@babel/eslint-parser`? There is `parser: 'babel-eslint'` in the linked issue https://github.com/ecomfe/eslint-config/issues/17.

**Comment by susiwen8** [comment]
```js
module.exports = {
    env: {
        browser: true,
        es2021: true,
    },
    extends: [
        '@ecomfe/eslint-config/strict',
        '@ecomfe/eslint-config/react/strict',
    ],
    parser: '@babel/eslint-parser',
    parserOptions: {
        ecmaFeatures: {
            jsx: true,
        },
        ecmaVersion: 12,
        sourceType: 'module',
        requireConfigFile: false,
    },
    plugins: [
        'react',
    ],
    rules: {
        'no-negated-condition': 'off',
        'complexity': 'off',
        'consistent-return': 'off',
        'react/jsx-no-bind': 'off',
        'react/no-array-index-key': 'off',
    },
};
```
That was old config. I have followed your suggestion above, change to `@babel/eslint-parser`. Issue still not resolved.
@mdjermanovic

**Comment by susiwen8** [comment]
> I couldn't reproduce this. Tried with the following config and source code:

As I have mentioned, this error occur in one particularly project repo,  I tried reproduce in new repo, but works like charm.

**Comment by susiwen8** [comment]
Also an interesting parts is that once `template-curly-spacing` disabled, `eslint` throw an new error

```shell
ESLint: 7.14.0

TypeError: Cannot read property 'range' of null
Occurred while linting /Users/susiwen/Documents/project/test.ts:1
    at OffsetStorage.setDesiredOffset (/Users/susiwen/Documents/project/node_modules/eslint/lib/rules/indent.js:341:45)
    at /Users/susiwen/Documents/project/node_modules/eslint/lib/rules/indent.js:1396:29
    at Array.forEach (<anonymous>)
    at Object.TemplateLiteral [as listener] (/Users/susiwen/Documents/project/node_modules/eslint/lib/rules/indent.js:1388:34)
    at /Users/susiwen/Documents/project/node_modules/eslint/lib/rules/indent.js:1634:55
    at Array.forEach (<anonymous>)
    at Program:exit (/Users/susiwen/Documents/project/node_modules/eslint/lib/rules/indent.js:1634:26)
    at /Users/susiwen/Documents/project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/susiwen/Documents/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
```

**Comment by mdjermanovic** [comment]
That's expected if `template-curly-spacing` doesn't work, the `babel-eslint` issue was observable with the `indent` rule, too.

Can you try to run this:

```js
npx eslint --print-config test.ts
```

and then check what's printed as `"parser"`

(`--print-config` shows the configuration used to lint particular file)

**Comment by susiwen8** [comment]
```json
{
  "env": {
    "browser": true,
    "es2021": true,
    "node": true,
    "es6": true
  },
  "globals": {},
  "parser": "/Users/susiwen/Documents/project/node_modules/@babel/eslint-parser/lib/index.js",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 12,
    "sourceType": "module",
    "requireConfigFile": false
  },
  "plugins": [
    "@babel",
    "react-hooks",
    "react"
  ],
  "rules": {
    "no-negated-condition": [
      "off"
    ],
    "complexity": [
      "off",
      10
    ],
    "consistent-return": [
      "off",
      {
        "treatUndefinedAsUnspecified": true
      }
    ],
    "react/jsx-no-bind": [
      "off",
      {
        "ignoreRefs": true,
        "allowArrowFunctions": false,
        "allowBind": false,
        "allowFunctions": false,
        "ignoreDOMComponents": false
      }
    ],
    "react/no-array-index-key": [
      "off"
    ],
    "template-curly-spacing": [
      "off",
      "never"
    ],
    "react-hooks/rules-of-hooks": [
      "error"
    ],
    "react-hooks/exhaustive-deps": [
      "error"
    ],
    "react/default-props-match-prop-types": [
      "off"
    ],
    "react/display-name": [
      "off"
    ],
    "react/forbid-component-props": [
      "off"
    ],
    "react/forbid-elements": [
      "off"
    ],
    "react/forbid-foreign-prop-types": [
      "warn"
    ],
    "react/forbid-prop-types": [
      "off"
    ],
    "react/jsx-boolean-value": [
      "error",
      "never"
    ],
    "react/jsx-closing-bracket-location": [
      "error",
      "line-aligned"
    ],
    "react/jsx-curly-spacing": [
      "error",
      "never"
    ],
    "react/jsx-equals-spacing": [
      "error",
      "never"
    ],
    "react/jsx-filename-extension": [
      "error",
      {
        "extensions": [
          ".js",
          ".jsx",
          ".es",
          ".tsx"
        ]
      }
    ],
    "react/jsx-first-prop-new-line": [
      "error",
      "multiline-multiprop"
    ],
    "react/jsx-handler-names": [
      "off",
      {
        "eventHandlerPrefix": ".*",
        "eventHandlerPropPrefix": "on"
      }
    ],
    "react/jsx-indent-props": [
      "error",
      4
    ],
    "react/jsx-indent": [
      "error",
      4
    ],
    "react/jsx-key": [
      "error"
    ],
    "react/jsx-max-props-per-line": [
      "error",
      {
        "when": "multiline"
      }
    ],
    "react/jsx-no-comment-textnodes": [
      "warn"
    ],
    "react/jsx-no-duplicate-props": [
      "error",
      {
        "ignoreCase": true
      }
    ],
    "react/jsx-no-literals": [
      "off"
    ],
    "react/jsx-no-target-blank": [
      "error"
    ],
    "react/jsx-no-undef": [
      "error"
    ],
    "react/jsx-pascal-case": [
      "error",
      {
        "allowAllCaps": true
      }
    ],
    "react/jsx-sort-props": [
      "off"
    ],
    "react/jsx-tag-spacing": [
      "error",
      {
        "closingSlash": "never",
        "beforeSelfClosing": "always",
        "afterOpening": "never"
      }
    ],
    "react/jsx-uses-react": [
      "off"
    ],
    "react/jsx-uses-vars": [
      "error"
    ],
    "react/jsx-wrap-multilines": [
      "error",
      {
        "declaration": true,
        "assignment": true,
        "return": true,
        "arrow": true
      }
    ],
    "react/no-children-prop": [
      "error"
    ],
    "react/no-danger-with-children": [
      "error"
    ],
    "react/no-danger": [
      "warn"
    ],
    "react/no-deprecated": [
      "warn"
    ],
    "react/no-did-mount-set-state": [
      "off"
    ],
    "react/no-did-update-set-state": [
      "off"
    ],
    "react/no-will-update-set-state": [
      "error"
    ],
    "react/no-direct-mutation-state": [
      "error"
    ],
    "react/no-find-dom-node": [
      "warn"
    ],
    "react/no-is-mounted": [
      "error"
    ],
    "react/no-multi-comp": [
      "error",
      {
        "ignoreStateless": true
      }
    ],
    "react/no-render-return-value": [
      "error"
    ],
    "react/no-set-state": [
      "off"
    ],
    "react/no-string-refs": [
      "error"
    ],
    "react/no-unescaped-entities": [
      "error"
    ],
    "react/no-unknown-property": [
      "error"
    ],
    "react/no-unused-prop-types": [
      "off"
    ],
    "react/prefer-es6-class": [
      "error",
      "always"
    ],
    "react/prefer-stateless-function": [
      "error"
    ],
    "react/prop-types": [
      "off"
    ],
    "react/react-in-jsx-scope": [
      "off"
    ],
    "react/require-default-props": [
      "off"
    ],
    "react/require-optimization": [
      "off"
    ],
    "react/require-render-return": [
      "error"
    ],
    "react/self-closing-comp": [
      "error",
      {
        "component": true,
        "html": false
      }
    ],
    "react/sort-prop-types": [
      "off"
    ],
    "react/style-prop-object": [
      "error"
    ],
    "react/void-dom-elements-no-children": [
      "error"
    ],
    "react/sort-comp": [
      "off",
      {
        "order": [
          "static-properties",
          "static-methods",
          "state",
          "properties",
          "lifecycle",
          "everything-else",
          "render"
        ],
        "groups": {
          "static-properties": [
            "displayName",
            "propTypes",
            "contextTypes",
            "childContextTypes",
            "mixins",
            "statics"
          ],
          "lifecycle": [
            "getDefaultProps",
            "getInitialState",
            "constructor",
            "getChildContext",
            "componentWillMount",
            "componentDidMount",
            "componentWillReceiveProps",
            "shouldComponentUpdate",
            "componentWillUpdate",
            "componentDidUpdate",
            "componentDidCatch",
            "componentWillUnmount"
          ]
        }
      }
    ],
    "accessor-pairs": [
      "error"
    ],
    "array-bracket-newline": [
      "warn",
      "consistent"
    ],
    "array-bracket-spacing": [
      "error",
      "never"
    ],
    "array-callback-return": [
      "error"
    ],
    "arrow-body-style": [
      "off"
    ],
    "arrow-parens": [
      "error",
      "as-needed"
    ],
    "arrow-spacing": [
      "error"
    ],
    "block-scoped-var": [
      "warn"
    ],
    "block-spacing": [
      "error",
      "never"
    ],
    "brace-style": [
      "off"
    ],
    "callback-return": [
      "off"
    ],
    "camelcase": [
      "error"
    ],
    "capitalized-comments": [
      "off"
    ],
    "class-methods-use-this": [
      "off"
    ],
    "comma-dangle": [
      "error",
      {
        "arrays": "always-multiline",
        "objects": "always-multiline",
        "imports": "always-multiline",
        "exports": "always-multiline",
        "functions": "never"
      }
    ],
    "comma-spacing": [
      "error",
      {
        "before": false,
        "after": true
      }
    ],
    "comma-style": [
      "error",
      "last"
    ],
    "computed-property-spacing": [
      "error",
      "never"
    ],
    "consistent-this": [
      "off"
    ],
    "constructor-super": [
      "error"
    ],
    "curly": [
      "error",
      "all"
    ],
    "default-case": [
      "off"
    ],
    "dot-location": [
      "error",
      "property"
    ],
    "dot-notation": [
      "error",
      {
        "allowKeywords": true,
        "allowPattern": ""
      }
    ],
    "eol-last": [
      "error",
      "always"
    ],
    "eqeqeq": [
      "error",
      "always",
      {
        "null": "ignore"
      }
    ],
    "for-direction": [
      "off"
    ],
    "func-call-spacing": [
      "error",
      "never"
    ],
    "func-name-matching": [
      "off"
    ],
    "func-names": [
      "warn",
      "always"
    ],
    "func-style": [
      "off"
    ],
    "generator-star-spacing": [
      "error",
      {
        "before": false,
        "after": true
      }
    ],
    "global-require": [
      "warn"
    ],
    "guard-for-in": [
      "warn"
    ],
    "handle-callback-err": [
      "off"
    ],
    "id-blacklist": [
      "off"
    ],
    "id-length": [
      "off"
    ],
    "id-match": [
      "off"
    ],
    "indent": [
      "error",
      4,
      {
        "SwitchCase": 1,
        "flatTernaryExpressions": false,
        "offsetTernaryExpressions": false,
        "ignoreComments": false
      }
    ],
    "indent-legacy": [
      "off"
    ],
    "init-declarations": [
      "warn"
    ],
    "jsx-quotes": [
      "error",
      "prefer-double"
    ],
    "key-spacing": [
      "error",
      {
        "beforeColon": false,
        "afterColon": true
      }
    ],
    "keyword-spacing": [
      "error"
    ],
    "line-comment-position": [
      "off"
    ],
    "linebreak-style": [
      "error",
      "unix"
    ],
    "lines-around-comment": [
      "off"
    ],
    "max-depth": [
      "warn",
      3
    ],
    "max-len": [
      "error",
      120,
      4,
      {
        "ignoreUrls": true
      }
    ],
    "max-lines": [
      "warn",
      800
    ],
    "max-nested-callbacks": [
      "off"
    ],
    "max-params": [
      "off"
    ],
    "max-statements": [
      "warn",
      30,
      {
        "ignoreTopLevelFunctions": true
      }
    ],
    "max-statements-per-line": [
      "error"
    ],
    "multiline-ternary": [
      "off"
    ],
    "new-cap": [
      "error"
    ],
    "new-parens": [
      "warn"
    ],
    "newline-per-chained-call": [
      "off"
    ],
    "no-alert": [
      "warn"
    ],
    "no-array-constructor": [
      "off"
    ],
    "no-await-in-loop": [
      "off"
    ],
    "no-bitwise": [
      "off"
    ],
    "no-buffer-constructor": [
      "warn"
    ],
    "no-caller": [
      "error"
    ],
    "no-case-declarations": [
      "error"
    ],
    "no-catch-shadow": [
      "off"
    ],
    "no-class-assign": [
      "error"
    ],
    "no-compare-neg-zero": [
      "error"
    ],
    "no-cond-assign": [
      "error"
    ],
    "no-confusing-arrow": [
      "error",
      {
        "allowParens": true
      }
    ],
    "no-console": [
      "error"
    ],
    "no-const-assign": [
      "error"
    ],
    "no-constant-condition": [
      "error"
    ],
    "no-continue": [
      "off"
    ],
    "no-control-regex": [
      "error"
    ],
    "no-debugger": [
      "error"
    ],
    "no-delete-var": [
      "error"
    ],
    "no-div-regex": [
      "off"
    ],
    "no-dupe-args": [
      "error"
    ],
    "no-dupe-class-members": [
      "error"
    ],
    "no-dupe-keys": [
      "error"
    ],
    "no-duplicate-case": [
      "error"
    ],
    "no-duplicate-imports": [
      "warn"
    ],
    "no-else-return": [
      "off"
    ],
    "no-empty": [
      "error"
    ],
    "no-empty-character-class": [
      "error"
    ],
    "no-empty-function": [
      "error"
    ],
    "no-empty-pattern": [
      "error"
    ],
    "no-eq-null": [
      "off"
    ],
    "no-eval": [
      "error"
    ],
    "no-ex-assign": [
      "error"
    ],
    "no-extend-native": [
      "error"
    ],
    "no-extra-bind": [
      "warn"
    ],
    "no-extra-boolean-cast": [
      "error"
    ],
    "no-extra-label": [
      "error"
    ],
    "no-extra-parens": [
      "error",
      "functions"
    ],
    "no-extra-semi": [
      "error"
    ],
    "no-fallthrough": [
      "error"
    ],
    "no-floating-decimal": [
      "error"
    ],
    "no-func-assign": [
      "warn"
    ],
    "no-global-assign": [
      "error"
    ],
    "no-implicit-coercion": [
      "off"
    ],
    "no-implicit-globals": [
      "off"
    ],
    "no-implied-eval": [
      "error"
    ],
    "no-inline-comments": [
      "off"
    ],
    "no-inner-declarations": [
      "error"
    ],
    "no-invalid-regexp": [
      "error"
    ],
    "no-invalid-this": [
      "off"
    ],
    "no-irregular-whitespace": [
      "error"
    ],
    "no-iterator": [
      "off"
    ],
    "no-label-var": [
      "off"
    ],
    "no-labels": [
      "off"
    ],
    "no-lone-blocks": [
      "off"
    ],
    "no-lonely-if": [
      "error"
    ],
    "no-loop-func": [
      "warn"
    ],
    "no-magic-numbers": [
      "off"
    ],
    "no-mixed-operators": [
      "off"
    ],
    "no-mixed-requires": [
      "off"
    ],
    "no-mixed-spaces-and-tabs": [
      "error"
    ],
    "no-multi-assign": [
      "warn"
    ],
    "no-multi-spaces": [
      "error",
      {
        "exceptions": {
          "Property": false
        },
        "ignoreEOLComments": false
      }
    ],
    "no-multi-str": [
      "warn"
    ],
    "no-multiple-empty-lines": [
      "warn"
    ],
    "no-negated-in-lhs": [
      "error"
    ],
    "no-nested-ternary": [
      "off"
    ],
    "no-new": [
      "error"
    ],
    "no-new-func": [
      "error"
    ],
    "no-new-object": [
      "error"
    ],
    "no-new-require": [
      "error"
    ],
    "no-new-symbol": [
      "error"
    ],
    "no-new-wrappers": [
      "error"
    ],
    "no-obj-calls": [
      "error"
    ],
    "no-octal": [
      "error"
    ],
    "no-octal-escape": [
      "error"
    ],
    "no-param-reassign": [
      "warn",
      {
        "props": true
      }
    ],
    "no-path-concat": [
      "off"
    ],
    "no-plusplus": [
      "off"
    ],
    "no-process-env": [
      "off"
    ],
    "no-process-exit": [
      "off"
    ],
    "no-proto": [
      "error"
    ],
    "no-prototype-builtins": [
      "off"
    ],
    "no-redeclare": [
      "error"
    ],
    "no-regex-spaces": [
      "error"
    ],
    "no-restricted-globals": [
      "off"
    ],
    "no-restricted-imports": [
      "off"
    ],
    "no-restricted-modules": [
      "off"
    ],
    "no-restricted-properties": [
      "off"
    ],
    "no-restricted-syntax": [
      "off"
    ],
    "no-return-assign": [
      "error",
      "except-parens"
    ],
    "no-return-await": [
      "error"
    ],
    "no-script-url": [
      "warn"
    ],
    "no-self-assign": [
      "error"
    ],
    "no-self-compare": [
      "error"
    ],
    "no-sequences": [
      "error"
    ],
    "no-shadow": [
      "off"
    ],
    "no-shadow-restricted-names": [
      "off"
    ],
    "no-spaced-func": [
      "error"
    ],
    "no-sparse-arrays": [
      "error"
    ],
    "no-sync": [
      "off"
    ],
    "no-tabs": [
      "warn"
    ],
    "no-template-curly-in-string": [
      "off"
    ],
    "no-ternary": [
      "off"
    ],
    "no-this-before-super": [
      "error"
    ],
    "no-throw-literal": [
      "warn"
    ],
    "no-trailing-spaces": [
      "error"
    ],
    "no-undef": [
      "error"
    ],
    "no-undef-init": [
      "warn"
    ],
    "no-undefined": [
      "off"
    ],
    "no-underscore-dangle": [
      "warn"
    ],
    "no-unexpected-multiline": [
      "error"
    ],
    "no-unmodified-loop-condition": [
      "warn"
    ],
    "no-unneeded-ternary": [
      "error"
    ],
    "no-unreachable": [
      "error"
    ],
    "no-unsafe-finally": [
      "error"
    ],
    "no-unsafe-negation": [
      "error"
    ],
    "no-unused-expressions": [
      "warn",
      {
        "allowShortCircuit": true,
        "allowTernary": false,
        "allowTaggedTemplates": false
      }
    ],
    "no-unused-labels": [
      "error"
    ],
    "no-unused-vars": [
      "error"
    ],
    "no-use-before-define": [
      "error",
      {
        "variables": false,
        "classes": false,
        "functions": true
      }
    ],
    "no-useless-call": [
      "warn"
    ],
    "no-useless-computed-key": [
      "error"
    ],
    "no-useless-concat": [
      "warn"
    ],
    "no-useless-constructor": [
      "error"
    ],
    "no-useless-escape": [
      "error"
    ],
    "no-useless-rename": [
      "error"
    ],
    "no-useless-return": [
      "error"
    ],
    "no-var": [
      "error"
    ],
    "no-void": [
      "error"
    ],
    "no-warning-comments": [
      "off"
    ],
    "no-whitespace-before-property": [
      "error"
    ],
    "no-with": [
      "error"
    ],
    "nonblock-statement-body-position": [
      "off"
    ],
    "object-curly-newline": [
      "error",
      {
        "consistent": true,
        "multiline": true
      }
    ],
    "object-curly-spacing": [
      "off"
    ],
    "object-property-newline": [
      "off"
    ],
    "object-shorthand": [
      "off",
      "consistent-as-needed"
    ],
    "one-var": [
      "error",
      "never"
    ],
    "one-var-declaration-per-line": [
      "error"
    ],
    "operator-assignment": [
      "off"
    ],
    "operator-linebreak": [
      "error",
      "before"
    ],
    "padded-blocks": [
      "off"
    ],
    "padding-line-between-statements": [
      "off"
    ],
    "prefer-arrow-callback": [
      "warn"
    ],
    "prefer-const": [
      "error"
    ],
    "prefer-destructuring": [
      "off"
    ],
    "prefer-numeric-literals": [
      "error"
    ],
    "prefer-promise-reject-errors": [
      "warn"
    ],
    "prefer-reflect": [
      "off"
    ],
    "prefer-rest-params": [
      "error"
    ],
    "prefer-spread": [
      "warn"
    ],
    "prefer-template": [
      "off"
    ],
    "quote-props": [
      "off"
    ],
    "quotes": [
      "error",
      "single"
    ],
    "radix": [
      "error"
    ],
    "require-await": [
      "warn"
    ],
    "require-jsdoc": [
      "off"
    ],
    "require-yield": [
      "error"
    ],
    "rest-spread-spacing": [
      "error",
      "never"
    ],
    "semi": [
      "error",
      "always"
    ],
    "semi-spacing": [
      "error"
    ],
    "semi-style": [
      "error",
      "last"
    ],
    "sort-imports": [
      "off"
    ],
    "sort-keys": [
      "off"
    ],
    "sort-vars": [
      "off"
    ],
    "space-before-blocks": [
      "error",
      "always"
    ],
    "space-before-function-paren": [
      "error",
      {
        "anonymous": "always",
        "named": "never"
      }
    ],
    "space-in-parens": [
      "error",
      "never"
    ],
    "space-infix-ops": [
      "error"
    ],
    "space-unary-ops": [
      "warn"
    ],
    "spaced-comment": [
      "error",
      "always"
    ],
    "strict": [
      "off"
    ],
    "switch-colon-spacing": [
      "error",
      {
        "before": false,
        "after": true
      }
    ],
    "symbol-description": [
      "warn"
    ],
    "template-tag-spacing": [
      "error",
      "never"
    ],
    "unicode-bom": [
      "warn"
    ],
    "use-isnan": [
      "error"
    ],
    "valid-jsdoc": [
      "off"
    ],
    "valid-typeof": [
      "error"
    ],
    "vars-on-top": [
      "off"
    ],
    "wrap-iife": [
      "error",
      "any"
    ],
    "wrap-regex": [
      "off"
    ],
    "yield-star-spacing": [
      "off"
    ],
    "yoda": [
      "warn"
    ],
    "@babel/object-curly-spacing": [
      "error",
      "never"
    ]
  },
  "settings": {
    "react": {
      "version": "detect"
    }
  },
  "ignorePatterns": []
}
```

It's `@babel/eslint-parser` @mdjermanovic

**Comment by mdjermanovic** [comment]
> It's `@babel/eslint-parser`

Looks like it is, thanks for checking!  

> As I have mentioned, this error occur in one particularly project repo, I tried reproduce in new repo, but works like charm.

It seems we're running out of options to figure out the problem without the repo where it occurs. Can you make a repro repo?

**Comment by susiwen8** [comment]
> It seems we're running out of options to figure out the problem without the repo where it occurs. Can you make a repro repo?

It's a company project, I'll try to reduce code to reproduce. Maybe this weekend.

**Comment by susiwen8** [comment]
@mdjermanovic I think I found the way to reproduce it.

## package.json
```json
  "devDependencies": {
    "@babel/core": "^7.12.7",
    "@babel/eslint-parser": "^7.12.1",
    "eslint": "^7.14.0"
  }
```

## eslintrc.js
```js
module.exports = {
    parser: '@babel/eslint-parser',
    parserOptions: {
        requireConfigFile: false,
    },
    rules: {
        "template-curly-spacing": "error",
    },
};
```

then `cd` to `node_modules/@babel/traverse` and `npm i`

I think there is a conflict with inner node_modules with outer node_modules

**Comment by susiwen8** [comment]
I tried debug myself, I have found out at line [here](https://github.com/babel/babel/blob/main/eslint/babel-eslint-parser/src/convert/convertAST.js#L146)

the result with `ast.program.body[0].declarations[0].init.properties[0].value.quasis[1]` is different when `@babel/traverse` has inner node_modules

the `range` is `[27, 27]` which cause the error, without inner node_modules `range` is `[26, 28]` which works fine

**Comment by mdjermanovic** [comment]
Does everything work well when you delete `node_modules` at the top level in your project and do a clean install?

> I think there is a conflict with inner node_modules with outer node_modules

I couldn't reproduce it with these steps. It might be that some of the babel packages hasn't updated certain dependency to the very last version, so this happens in edge cases after updating existing `node_modules`.

**Comment by susiwen8** [comment]
> Does everything work well when you delete node_modules at the top level in your project and do a clean install?

Sure, I made a new repo, create a new package.json, then do `npm i`, and run `npm run lint` see weather process work or not. Turns out it work. Then I have `cd` to `node_modules/@babel/traverse`, run `npm i`. After this was done, go back to repo root,  run `npm run lint`, process broke.

Then I have deleted top level `node_modules` (I didn't deleted package-lock.json), and rerun  `npm i && npm run lint`, eslint work. `cd` to `node_modules/@babel/traverse`, run `npm i && cd ../../../ && npm run lint`. Broke.  :joy::joy::joy:

**Comment by susiwen8** [comment]
I think you can close this issue now, cause it's not eslint problem.

**Comment by ImreBoersma** [comment]
Got a fix for this. Run the following npm commands to update the eslint packages manually(I think):

`npm install --save-dev @babel/types@7.2.0 @babel/traverse@7.1.6`
`npm dedupe`
`npm uninstall --save-dev @babel/types @babel/traverse`

I don't really know how it works, but it worked for me.

**Comment by mdjermanovic** [comment]
I'm closing this issue because it's definitely not a problem with ESLint itself.

I also believe that this has been fixed in Babel, but if it still happens in some cases, it would be probably good to open an issue in https://github.com/babel/babel repo. Maybe some dependency needs to be updated.

**Comment by nelilly** [comment]
> Got a fix for this. Run the following npm commands to update the eslint packages manually(I think):
> 
> `npm install --save-dev @babel/types@7.2.0 @babel/traverse@7.1.6`
> `npm dedupe`
> `npm uninstall --save-dev @babel/types @babel/traverse`
> 
> I don't really know how it works, but it worked for me.

This worked for me as well.
