### ISSUE TITLE
Docs: Fixed Sidebar

### ISSUE THREAD

**Issue by Jay-Karia** [eslint/eslint#18859]
### Docs page(s)

On of the page: https://eslint.org/docs/latest/extend/custom-rules#providing-suggestions

### What documentation issue do you want to solve?

On scrolling down the page, after a certain height the sidebar is not visible and accessible.

### What do you think is the correct solution?

I'd like to make the sidebar fixed for easy access at any section of the page.

### Participation

- [x] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
I'm not a fan of a fixed sidebar. That means we'll have to have a scrollbar on the sidebar to make sure you can always access the whole thing, and I think that looks very messy.

Curious what others think.

@eslint/eslint-team

**Comment by Jay-Karia** [comment]
We can make the scrollbar visible only on hover

**Comment by fasttime** [comment]
I see on that page a sidebar on the left and one on the right. The right sidebar is already fixed, and has a vertical scrollbar to see the whole content. So this proposal is about fixing the left sidebar too?

![Image](https://github.com/user-attachments/assets/1b3ead33-13e1-4202-a4fd-a80730d122a7)

**Comment by Jay-Karia** [comment]
The right sidebar seems fine, 
but the left sidebar is not fixed, we can change that.

**Comment by harish-sethuraman** [comment]
I don't think its a good idea. There are also pages where the content is very less like https://eslint.org/docs/latest/integrate/ in this case the left bar and right bar will both have scroll?

**Comment by Jay-Karia** [comment]
I was thinking to make the behavior of left sidebar similar to right sidebar

**Comment by Tanujkanti4441** [comment]
> There are also pages where the content is very less like https://eslint.org/docs/latest/integrate/ in this case the left bar and right bar will both have scroll?

I think another way to look at it is if we have a fix sidebar on left then we can avoid continue scrolling of the main docs page even when there is nothing to show. like 


![Image](https://github.com/user-attachments/assets/56edb02f-388f-4b43-bf13-5916b1a55403)

what do you think?

**Comment by nzakas** [comment]
Scrolling doesn't bother me.

**Comment by Jay-Karia** [comment]
So we have to make the behavior of left sidebar as right ?

**Comment by nzakas** [comment]
I think we should just leave everything as it is.

Does anyone on the team feel strongly that we *should* change the left scrollbar?

**Comment by amareshsm** [comment]
IMO I'm okay with making the sidebar fixed. Here are the pros and cons of this approach:

**Pros:**
Improved Navigation and Usability: Provides constant access to the left side bar contents, making it easier for users to navigate the documentation.
Consistent User Experience: Maintains seamless access to navigation options, enhancing the overall user experience.

**Cons:**
Potential for a Messy Appearance: The page might look messy with a fixed sidebar.

But since we have dedicated space on both the right and left for sidebars, we will end up utilizing this space effectively. If the left sidebar is not fixed, the space on the left will remain empty.

I'm open to feedback and other opinions on this approach.

**Comment by harish-sethuraman** [comment]
> Does anyone on the team feel strongly that we should change the left scrollbar?

nope it is good as it is what I feel. As @amareshsm added 

> Potential for a Messy Appearance: The page might look messy with a fixed sidebar.

this might also have a scrollbar on windows on both sides?

**Comment by Tanujkanti4441** [comment]
I also don't have strong opinions on fixed sidebar, right now we already have a back to top button so we can reach to the sidebar in seconds even if the pages are long. Also i feel list of the items in left sidebar is not that much long so we can access any item easily.
