### ISSUE TITLE
no-undef error on ES6 import

### ISSUE THREAD

**Issue by ai** [eslint/eslint#1978]
As I understand ESLint doesn’t understand that `import` create variable.

So I get a `'Warning' is not defined` error on line 2 of this code:

```js
import Warning from '../lib/warning';
var warn = new Warning('text');
```

I uses eslint 0.16.1 and my `.eslintrc` is:

```js
{
    "ecmaFeatures": {
        "modules": true,
        "module":  true
    },
    "env": {
        "mocha": true,
        "node":  true,
        "es6":   true
    }
}
```

/cc @nzakas

**Comment by AsaAyers** [comment]
I'm having the same issue. I've turned on all of the `ecmaFeatures`.

Based on having seen that #1543 wasn't picking up the rest args I was figuring this is probably an issue with escope. escope [definitely supports imports](https://github.com/estools/escope/blob/master/test/es6-import.coffee)

**Comment by nzakas** [comment]
Could be an escope issue, but also could be the rule itself. Need to investigate.

**Comment by jasonkuhrt** [comment]
I'm also seeing this.

Source:
```js
import Promise from 'bluebird'
import { partial as par, compose, merge, waitForEvent } from 'lodash'
import shortid from 'shortid'
import Log from './log'
import JsonStream from 'json-stream2'



export default function DeviceConnection(socket) {

  socket.subscribers = {}

  socket.log = Log.child(socket.profile) // <--- ERROR no un-def
```
```
λ cat .eslintrc
---
  env:
    node: true
    mocha: true
    browser: true
    es6: true
  ecmaFeatures:
    modules: true
  rules:
    no-underscore-dangle: false
    space-in-parens: "never"
    space-before-blocks: "always"
    space-in-brackets: "always"
    no-lonely-if: true
    default-case: true
    quotes: [1, "single", "avoid-escape"]
    strict: false
    no-use-before-define: "nofunc"
    camelcase: false
    new-cap: "newIsCap"
    curly: [2, "multi-line"]
    semi: [0, "always"]
```

**Comment by fczuardi** [comment]
the link sent by @AsaAyers is a good hint, the identifiers of an import are not expected to be on global scope (scopes[0]) https://github.com/estools/escope/blob/master/test/es6-import.coffee#L39 but on a separate one instead https://github.com/estools/escope/blob/master/test/es6-import.coffee#L42

The no-undef rule uses a context.getScope https://github.com/eslint/eslint/blob/master/lib/rules/no-undef.js#L99 that returns only scopes[0] https://github.com/eslint/eslint/blob/master/lib/eslint.js#L953 and the imported variable is not there because it is stored in a different object (with scopes type module). 

The eslint-babel parser project is having this same bug https://github.com/babel/babel-eslint/issues/15 here is one patch example of a fork that attempts to fix this: https://github.com/BenoitZugmeyer/babel-eslint/commit/f9a84aabc05cba61b4b941dcc4e2d986d066e55c

**Comment by xjamundx** [comment]
Not yet helpful, but diving a bit into the `getScope` method I see the following when I log _all of the_ scope types and variables for the following code.

```js
import $ from 'jquery';
import BaseView from 'BaseView';
import NotifcationView from 'view/notification';
```
Here is the logging I added to the `getScope()` method:
```js
currentScopes.forEach(function(scope) {
	console.log(scope.type, scope.variables.map(function(x) { return x.name; }), "\n");
});
```

Here is the result:
```
global [ 'Array',
  'ArrayBuffer',
  'Boolean',
  // ... all of the rest of the expected globals
 ] 
function [ 'arguments' ] 
module [] 
function [ 'arguments', 'loadError' ] 
block [ 'bodyData' ] 
block [] 
block [] 
function [ 'arguments' ] 
function [ 'arguments' ] 
function [ 'arguments', 'event' ] 
```

So I'm not sure if we're getting what we need from `escope` (or I'm logging the wrong things...)

**Comment by fczuardi** [comment]
Here is a similar testcase to help understand the issue:

```javascript
// install each tip of the branch with:
//     npm install jquery/esprima#harmony
//     npm install eslint/espree
//     npm install estools/escope

var esprima = require('esprima');
var espree = require("espree");
var escope = require('escope');

var code = 'import v from "mod"';

var esprimaConfig = {
    sourceType: 'module'
};
var escopeConfig = {
    ecmaVersion: 6,
    sourceType: 'module'
};

var ast1 = esprima.parse(code, esprimaConfig);
var ast2 = espree.parse(code, esprimaConfig);

var scopeManager1 = escope.analyze(ast1, escopeConfig);
var scopeManager2 = escope.analyze(ast2, escopeConfig);

console.log('esprima harmony:', scopeManager1.scopes[1].variables);
console.log('eslint espree:', scopeManager2.scopes[1].variables);

```

Output:
```
esprima harmony: [ { name: 'v',
    identifiers: [ [Object] ],
    references: [],
    defs: [ [Object] ],
    tainted: false,
    stack: true,
    scope: 
     { type: 'module',
       set: {},
       taints: {},
       dynamic: false,
       block: [Object],
       through: [],
       variables: [Circular],
       references: [],
       variableScope: [Circular],
       functionExpressionScope: false,
       directCallToEvalScope: false,
       thisFound: false,
       __left: null,
       upper: [Object],
       isStrict: true,
       childScopes: [] } } ]
eslint espree: []
```

**Comment by nzakas** [comment]
This is an interesting discussion, but it should be taking place in an escope issue, not here.

It looks like escope hasn't been updated to respect the latest AST structure for modules.

**Comment by fczuardi** [comment]
is this the https://github.com/estools/escope/issues/33 or a new unfilled one?

**Comment by nzakas** [comment]
Best to start a new one.

**Comment by fczuardi** [comment]
filed https://github.com/estools/escope/issues/51

**Comment by nzakas** [comment]
Thanks!

**Comment by ai** [comment]
@fczuardi `estools/escope#51` is fixed. does we need bugfix release for ESLint or i just need to update `node_modules`?

**Comment by fczuardi** [comment]
I don't know if that fix also fixes this one, need to test it, can you please try updating your node_modules/eslint/node_modules/escope to the tip of their master and see if it works please?

**Comment by ai** [comment]
@fczuardi seems like they didn’t release it yet.

Anyway there is same issue with fresh `node_modules`.

**Comment by fczuardi** [comment]
you don't need to wait for a release, you can always install tip of the master of any npm package with ```npm install githubuser/project``` in the case of scope, after downloading the master branch with npm install you will also have to run a build task to build their library, but it should be as simple as a ```node_modules/.bin/gulp build``` inside their module directory

**Comment by ai** [comment]
@fczuardi it is open soource project, so I can’t ask every contributor to has so difficult install process. Also I prefer to wait rather that create difficult `script` tasks in Travis CI.

**Comment by ai** [comment]
@fczuardi but @keithamus [said](https://github.com/estools/escope/pull/52#issuecomment-78017322) that this fix is works for him.

**Comment by ai** [comment]
Fixed with latest `escope` 2.0.7 update

**Comment by fczuardi** [comment]
eslint still has 2.0.6 https://github.com/eslint/eslint/blob/master/package.json#L42 have you tested before closing the bug?

**Comment by ai** [comment]
`2.0.7` is in `^2.0.6` dependency, becuase of `^`. And I tested it in PostCSS project.

**Comment by emmenko** [comment]
@fczuardi since it's specified with caret `^` you can install `eslint` and the patch version of `escope` gets installed (no need to release a new version).

**Comment by emmenko** [comment]
PS: I can confirm it's working now! :+1:

**Comment by fczuardi** [comment]
nice \o/

**Comment by wavded** [comment]
This resolved the `undef` issue, great work... unfortunately, now I'm getting this one... https://github.com/eslint/eslint/issues/1985

**Comment by nzakas** [comment]
Just reopening to bump the version. :)

**Comment by ai** [comment]
Seems like issue is back (I updated to 0.16.2 and reinstall all `node_modules`)

**Comment by nzakas** [comment]
Yeah, I had to hard code escope to an old version because the new version caused other errors. Sorry about that.

**Comment by emmenko** [comment]
@nzakas what's the status on this then? Should we just ignore the rule for now?
Thanks...

**Comment by AsaAyers** [comment]
The workaround I'm using for now is to declare the variables as global when I import. Obviously ideal, but it at least doesn't require me to turn off the rule and I get rid of the false errors.

    /*global foo */
    import foo from "foo"

**Comment by ivanoats** [comment]
My work-around was to go into node_modules/eslint/ and edit package.json to require escope 2.0.7 then nom install escope@2.0.7 from there. This might have to be done in your global packages, too, for me it was `/Users/ivan/.nvm/v0.10.36/lib/node_modules/eslint`

**Comment by AsaAyers** [comment]
Upgrading to 2.0.7 broke other things whichis why it was not in the latest release: https://github.com/eslint/eslint/issues/2001

**Comment by zpratt** [comment]
I too am using the inline global variable whitelist as a temp workaround. Not ideal, but easy to remove once the issue is fixed.

**Comment by nzakas** [comment]
@emmenko we are waiting for a fix from escope, so you'll need to workaround this for now. When there is an update, it will be posted here.

**Comment by emmenko** [comment]
@nzakas perfect, many thanks! :)

**Comment by nzakas** [comment]
Going to see if I can workaround while waiting for escope.

**Comment by wavded** [comment]
Maybe this is in line with this issue, but using 0.17, given this code (with es6 env and modules turned on):

```js
import auth from 'basic-auth'
var foo = {}
var creds = auth(foo)
foo.creds = {
  username: creds.name,
  password: creds.pass
}
```

Gives this error:

```
/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/rules/no-func-assign.js:42
                if (def.name.name === name && def.type === "FunctionName") {
                            ^
TypeError: Cannot read property 'name' of undefined
    at checkIfIdentifierIsFunction (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/rules/no-func-assign.js:42:29)
    at EventEmitter.AssignmentExpression (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/rules/no-func-assign.js:73:17)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.enter (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/eslint.js:735:25)
    at Controller.__execute (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/eslint.js:728:24)
    at processFile (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/cli-engine.js:193:27)
    at /Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/cli-engine.js:293:26
```

Another one is this code:

```js
import auth from 'basic-auth'
```

Gives this error:

```
/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/rules/no-unused-vars.js:43
            if (definition.type === "VariableDeclarator") {
                          ^
TypeError: Cannot read property 'type' of undefined
    at isExported (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/rules/no-unused-vars.js:43:27)
    at EventEmitter.Program:exit (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/rules/no-unused-vars.js:120:70)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.leave (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/eslint.js:743:25)
    at Controller.__execute (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:481:28)
    at EventEmitter.module.exports.api.verify (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/eslint.js:728:24)
    at processFile (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/cli-engine.js:193:27)
    at /Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/cli-engine.js:293:26
```

**Comment by nzakas** [comment]
@wavded that's a completely separate issue, can you open a separate issue?

**Comment by wavded** [comment]
Sure thing. #2071

**Comment by ai** [comment]
Maybe I can help? 1.8 release and still not fix this issue (but we had some fix before)

**Comment by nzakas** [comment]
The "fix" from before resulted in regressions in other areas, which is why it was removed. The only real solution here is to get to the point where we can upgrade escope. To do that, the parser needs updating.

**Comment by nzakas** [comment]
Fixed by #2235

**Comment by FrenchBen** [comment]
Still having the same error 'Illegal import declaration (undefined) in atom.io:
`eslint@1.0.0`
`espree@2.2.3`
`escope@3.2.0`

```javascript
import _ from 'underscore';
import Promise from 'bluebird';
```

**Comment by IanVS** [comment]
@frenchben, what is your `.eslintrc`? You will need to specify `ecmaFeatures: { modules: true }` as mentioned in http://eslint.org/docs/user-guide/configuring#specifying-language-options

**Comment by FrenchBen** [comment]
@IanVS eslintrc is as follow:

```YAML
root: true

ecmaFeatures:
    modules: true
    jsx: true
    arrowFunctions: true
    blockBindings: true

env:
    node: true
    es6: true
    browser: true

extends:
    "eslint:recommended"
```

**Comment by IanVS** [comment]
Do you get the same error if you run eslint directly, outside of atom?

**Comment by FrenchBen** [comment]
It deosn't seem to complain about it - Guess the plugin/package for atom is to blame :[ ?
Package is: https://atom.io/packages/linter-eslint

**Comment by IanVS** [comment]
I'd suggest opening an issue there, if one does not already exist.

**Comment by FrenchBen** [comment]
will do - thanks for the quick response.
