### ISSUE TITLE
Bug: ESLint 9.x no longer follows symlinks when resolving files

### ISSUE THREAD

**Issue by xenobytezero** [eslint/eslint#19963]
### Environment

Node version: 22.4.1
npm version: 10.8.1
Local ESLint version: 9.31.0
Global ESLint version: 9.31.0
Operating System: linux 6.6.87.2-microsoft-standard-WSL2

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```js
import { defineConfig } from "eslint/config";
import markdown from "@eslint/markdown";

export default defineConfig([
  {
    ignores: ['.next', '.source', 'node_modules'],
  },
  markdown.configs.recommended
]);
```
</details>

```js
<!-- Paste your code here -->
```

### What did you expect to happen?

I am attempting to lint a Markdown based documentation site, where a number of the content folders are symlinked in. 

It looks like ESLint is not following those symlinks and finding the files inside them.

### What actually happened?

Having a look around the source, it looks like the move to [humanfs](https://github.com/humanwhocodes/humanfs) in ESLint 9.13 (specifically [this commit](https://github.com/eslint/eslint/commit/2ff0e51cedaab967b7ce383437f64b4a6df8608d)) might be responsible, as the `walk()` function does not continue if the folder is a symlink. It checks the `.isDirectory` member on the item, which is false for symlinks (there is a seperate `isSymlink` member). This is internal to the `.walk()` function so afaik its not possible to configure this from the outside.

### Link to Minimal Reproducible Example

https://github.com/xenobytezero/bugrepro-eslint-symlinks

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Repro Instructions

1. Clone repo above
2. `npm install`
3. `npm run make-link`
4. `npm run lint:inspect`

The config inspector is showing that it finds the `src/local/code.js`, but does not find the `src/link-src/code.js`. Removing the `link-src` folder from the `ignores` list results in it finding the file at the root of the source, but not via the symlink.

**Comment by xenobytezero** [comment]
There is a repro repo linked in the ticket, despite the tag.

**Comment by snitin315** [comment]
I'm looking into it. Meanwhile, @xenobytezero Is it possible for you to provide a repro in which it is working as expected (in an older version or legacy config)?

**Comment by xenobytezero** [comment]
I have pushed a new version of the example.

After doing some more testing it looks like this is actually an issue with the old vs. new config files.

The example now has a `.eslintrc` and a `eslint.config.js`, both configured identically. When running with ESLint 8.57.1, if you use the old config file, ESLint correctly follows the symlink. If you delete the `.eslintrc` and rename the `eslint.config.js`, it no longer folllows the symlink.

**Comment by nzakas** [comment]
I'll take a look at this.

**Comment by bitpshr** [comment]
Confirming this is still reproducible on 10.7.0 (Node 22, @humanfs/node 0.16.8). Minimal repro:

```
mkdir -p repro/src/local repro/external && cd repro
printf 'const a = 1;\n' > src/local/code.js
printf 'const b = 1;\n' > external/code.js
ln -s ../external src/link-src
printf 'export default [{ rules: { "no-unused-vars": "error" } }];\n' > eslint.config.js
printf '{ "type": "module", "private": true }\n' > package.json
npm i eslint

npx eslint src            # only flags src/local/code.js, the file under link-src is skipped
npx eslint src/link-src   # lints it fine when you point straight at it
```

If you point ESLint straight at the symlinked path it lints the file fine, so I think the problem is just the directory walk not following the symlink during discovery. That fits it being flat-config specific, since the legacy enumerator walked with fs and followed symlinks.

I think the real issue is humanfs's `walk()`, which only recurses when `isDirectory` is true. For a symlinked directory that's false (`isSymlink` is the one that's true), so it never descends and ESLint's filters never see the files inside. I think the cleanest fix is upstream in humanfs, either following symlinked directories or adding an option. Happy to open a PR with the preferred approach.

I think we can remove the `repro:needed` label on this one.
