### ISSUE TITLE
leading forward slash of inline comment removed

### ISSUE THREAD

**Issue by jDmacD** [eslint/eslint#7603]
**Tell us about your environment**
* Window 7 
* **ESLint Version: v3.6.1**
* **Node Version: v4.4.7**
* **npm Version: 3.10.3**

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```
{
  "env": {
    "browser": true,
    "amd": true
  },
  "globals": {},
  "rules": {
    "semi": [
      "error",
      "always"
    ],
    "no-bitwise": 0,
    "no-cond-assign": 0,
    "camelcase": 2,
    "curly": 2,
    "no-debugger": 0,
    "eqeqeq": 2,
    "no-eq-null": 2,
    "no-eval": 0,
    "no-unused-expressions": 2,
    "guard-for-in": 0,
    "block-scoped-var": 2,
    "strict": 0,
    "comma-dangle": [
      "error",
      "never"
    ],
    "lines-around-directive": [
      "error",
      {
        "before": "never",
        "after": "always"
      }
    ],
    "object-curly-newline": [
      "error",
      "always"
    ],
    "wrap-iife": [
      2,
      "any"
    ],
    "keyword-spacing": [
      "error",
      {
        "before": true
      }
    ],
    "key-spacing": [
      "error",
      {
        "beforeColon": false
      }
    ],
    "no-iterator": 0,
    "no-use-before-define": 0,
    "comma-style": [
      2,
      "last"
    ],
    "space-before-blocks": [
      2,
      "always"
    ],
    "space-before-function-paren": [
      2,
      "always"
    ],
    "no-trailing-spaces": [
      2,
      {
        "skipBlankLines": true
      }
    ],
    "space-infix-ops": [
      2,
      {
        "int32Hint": false
      }
    ],
    "no-mixed-spaces-and-tabs": 2,
    "no-loop-func": 2,
    "no-multi-str": 0,
    "new-cap": 2,
    "no-caller": 2,
    "no-empty": 0,
    "no-new": 2,
    "no-plusplus": 0,
    "no-proto": 0,
    "no-script-url": 2,
    "no-shadow": 2,
    "dot-notation": 2,
    "no-new-func": 0,
    "no-new-wrappers": 0,
    "no-undef": 2,
    "no-unused-vars": 2,
    "no-invalid-this": 0,
    "no-with": 0,
    "max-len": [
      2,
      {
        "code": 120,
        "ignoreComments": true
      }
    ],
    "indent": [
      "error",
      "tab"
    ],
    "quotes": [
      "error",
      "double",
      {
        "avoidEscape": true
      }
    ],
    "quote-props": [
      2,
      "as-needed",
      {
        "unnecessary": true
      }
    ],
    "complexity": [
      2,
      10
    ]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

ran `eslint filename.js --fix`

```js
modules.exports = {
	foo: function (arg1, arg2, arg3) {},
	bar: /*static*/ function (arg1, arg2, arg3) {},
	baz /*static*/ : function (arg1, arg2, arg3) {}
};
```

**What did you expect to happen?**

The inline comment after **baz** to remain intact.

```js
modules.exports = {
	foo: function (arg1, arg2, arg3) {},
	bar: /*static*/ function (arg1, arg2, arg3) {},
	baz /*static*/ : function (arg1, arg2, arg3) {}
};
```

**What actually happened? Please include the actual, raw output from ESLint.**

```sh
  61:5  error  Parsing error: Unexpected token *

✖ 1 problem (1 error, 0 warnings)
```

The forward slash after **baz** has been removed
```js

modules.exports = {
	foo: function (arg1, arg2, arg3) {},
	bar: /*static*/ function (arg1, arg2, arg3) {},
	baz*static*/ : function (arg1, arg2, arg3) {}
};
```

**Comment by platinumazure** [comment]
Can you please try with latest ESLint? There were some bugs with the fixer in `object-shorthand` which we fixed with our most recent minor release.

**Comment by jDmacD** [comment]
@platinumazure I updated to version 3.10.1 but unfortunately the issue persists.

**Comment by not-an-aardvark** [comment]
I can reproduce this. It's caused by the `key-spacing` fixer.

**Comment by not-an-aardvark** [comment]
PR up at https://github.com/eslint/eslint/pull/7607

**Comment by jDmacD** [comment]
That works. Thanks for the fast turn around.
