### ISSUE TITLE
indent outerIIFEBody --fix not fixing comments

### ISSUE THREAD

**Issue by freshp86** [eslint/eslint#8478]
ESLint Version: v3.19.0
Node Version: v6.10.1

```js
module.exports = {
  env: {
    browser: true,
    es6: true,
  },
  root: true,
  extends: 'eslint:recommended',
  parserOptions: {
    sourceType: 'module',
  },
  rules: {
    indent: ['error', 2, {
      outerIIFEBody: 0,
      FunctionDeclaration: {'body': 1, 'parameters': 2},
      ArrayExpression: 1,
      ObjectExpression: 1, 
      MemberExpression: 2, 
      SwitchCase: 1,
    }],
  },
};
```
**What did you do? Please include the actual source code causing the issue.**

```js
(function() {
  // Hello world
  console.log('foo');
})();
```

**What did you expect to happen?**

```js
(function() {
// Hello world
console.log('foo');
})();
```

**What actually happened?**
The comment was not fixed.
```js
(function() {
  // Hello world
console.log('foo');
})();
```

**Comment by not-an-aardvark** [comment]
Thanks for the report. This was a known issue with the `indent` rule in 3.x -- in fact, it didn't validate the indentation of comments at all. The issue was fixed by #7618, so please wait until the next release. (Alternatively, you can install `eslint@4.0.0-alpha.0` to run an experimental version of the release.)

**Comment by freshp86** [comment]
@not-an-aardvark: I tried v4.0.0-alpha.0, and the issue seems only partially fixed. Specifically if I use as a rule
```js
...
indent: ['error', 2, {
  outerIIFEBody: 0,
}]
...
```
Then the code is fixed correctly from
```js
(function() {
  // Hello world
  console.log('foo');
})();
```
to
```js
(function() {
// Hello world
console.log('foo');
})();
```
But if I use 
```js
...
indent: ['error', 2, {
  outerIIFEBody: 1,
}]
...
```
then the following code
```js
(function() {
  // Hello world
  console.log('foo');
})();
```

is changed to
```js
(function() {
  // Hello world
console.log('foo');
})();
```
where the commented remains at the wrong indentation level of +2. Should this bug be re-opened?

**Comment by not-an-aardvark** [comment]
I don't understand your second example. With this config:

```js
...
indent: ['error', 2, {
  outerIIFEBody: 1,
}]
...
```

the following code is correct, and isn't autofixed at all:

```js
(function() {
  // Hello world
  console.log('foo');
})();
```

**Comment by freshp86** [comment]
Oops, I messed up my copy paste buffers. Clarifying below: If I use 
```js
...
indent: ['error', 2, {
  outerIIFEBody: 1,
}]
...
```
then the following code
```js
(function() {
// Hello world
console.log('foo');
})();
```

is changed to
```js
(function() {
// Hello world
  console.log('foo');
})();
```
where the comment remains at the wrong indentation level of 0. Sorry for the confusion, I hope it is clearer now.

**Comment by not-an-aardvark** [comment]
That's also working as intended -- see the explanation in https://github.com/eslint/eslint/issues/8445.
