### ISSUE TITLE
v4.14.0 scope analysis issue with babel-eslint

### ISSUE THREAD

**Issue by steida** [eslint/eslint#9762]
For some reason, after update:

```
ERROR  Failed to compile with 1 errors                                                                                                    00:04:50
error  in ./pages/_document.js?entry

Module build failed: TypeError: Cannot read property 'type' of undefined
    at isForInRef (/Users/steida/dev/este/node_modules/eslint/lib/rules/no-unused-vars.js:410:24)
    at variable.references.some.ref (/Users/steida/dev/este/node_modules/eslint/lib/rules/no-unused-vars.js:447:21)
    at Array.some (<anonymous>)
    at isUsedVariable (/Users/steida/dev/este/node_modules/eslint/lib/rules/no-unused-vars.js:446:40)
    at collectUnusedVariables (/Users/steida/dev/este/node_modules/eslint/lib/rules/no-unused-vars.js:569:26)
    at Program:exit (/Users/steida/dev/este/node_modules/eslint/lib/rules/no-unused-vars.js:621:36)
    at listeners.(anonymous function).forEach.listener (/Users/steida/dev/este/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/steida/dev/este/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/steida/dev/este/node_modules/eslint/lib/util/node-event-generator.js:251:26)
```

**Comment by steida** [comment]
4.13.1

**Comment by ilyavolodin** [comment]
Could you provide a sample of the code where this is failing?

**Comment by steida** [comment]
github.com/este/este

`yarn deps` to update eslint

**Comment by platinumazure** [comment]
@steida Try `eslint --debug` so you can see what file it's running on before crashing. Then you could provide the contents of that file, or try to narrow it down further. Without a code sample, there's not much we can investigate unless someone is willing to take the time to clone your repo... Thanks for understanding!

**Comment by steida** [comment]
Sure. Once I figure out how to run debug mode within webpack integration.

```
at Object.emit (/Users/steida/dev/este/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/steida/dev/este/node_modules/eslint/lib/util/node-event-generator.js:251:26)

 @ multi ./pages/_document.js?entry

(node:80698) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead
```

**Comment by steida** [comment]
Sorry, I don't know how to run eslint in debug mode from eslint-loader. Maybe later...

**Comment by le0nik** [comment]
Here's a minimal example of code it's failing on in my case. It doesn't fail i remove `@myDecorator` line or use `eslint@<=4.13.1`. Parser is set to `babel-eslint`.

```js
function myDecorator(SomeClass) {
  return SomeClass;
}

@myDecorator
class MyClass {
}
```

**Comment by not-an-aardvark** [comment]
@le0nik Thanks, that's very useful info. Are you able to reproduce the issue without `babel-eslint`? It's possible this is caused by something that `babel-eslint` is doing to modify ESLint's scoping behavior. (Actually, in this release we created a [new scoping API](https://eslint.org/blog/2017/12/eslint-v4.14.0-released#highlights) so that parsers wouldn't need to monkeypatch scoping behavior, but it's possible that we broke some existing interactions with the changes we made internally for that API.)

**Comment by dashed** [comment]
Getting similar issues with flow code.

```js
$ yarn lint
yarn run v1.3.2
$ eslint src test
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined

....
```

**Comment by le0nik** [comment]
@not-an-aardvark it doesn't work with decorators without `babel-eslint`. I get

```
5:1  error  Parsing error: Unexpected character '@'
```

**Comment by not-an-aardvark** [comment]
@le0nik To clarify, I was trying to ask if this issue occurs when you're neither using `babel-eslint` nor non-standard syntax. (As you noticed, if you only remove `babel-eslint` then the default parser won't be able to parse your code.)

**Comment by not-an-aardvark** [comment]
cc @mysticatea

**Comment by le0nik** [comment]
Just removed all uses of decorators in my project. In this case there is no error with and without `babel-eslint`.

**Comment by not-an-aardvark** [comment]
Also see: https://github.com/babel/babel-eslint/pull/542

**Comment by not-an-aardvark** [comment]
This issue should be fixed if you upgrade to the latest version of `babel-eslint`.

**Comment by ndelangen** [comment]
@not-an-aardvark I tried babel-eslint `8.1.0` and was still experiencing the issue.

**Comment by mikeconwell** [comment]
@not-an-aardvark , We are using a number of babel* products, but not babel-eslint, and experience same issue with 4.14.0.   Having to lock in at 4.13.1.

**Comment by not-an-aardvark** [comment]
@mikeconwell Would you mind creating a new issue with more information?

**Comment by mikeconwell** [comment]
@not-an-aardvark I'll put the work on that team to update dependencies citing this task.  May come back later. Thanks for quick response.
